### ISSUE TITLE
README is out-of-date

### ISSUE THREAD

**Issue by carlsmedstad** [ThemerCorp/themer.lua#29]
Hey :wave: 

Thanks for developing this!

Since the API has changed in the `dev` branch the README is out-of-date. Specifically:

```lua
use({
	"narutoxy/themer.lua",
	branch = "dev",	-- I recommend dev branch because it has more plugin support currently
	module = "themer",	-- load it as fast as possible
	config = function()
		-- vim.cmd("colorscheme dark_cpt") -- you can also do this
		require("themer").load("dark_cpt")
	end,
})
```

It might be a good idea to remove `branch = "dev"` and possibly also add examples for the API of the `dev` branch.

Another issue I stumbled upon is that Packer doesn't load the module if `module = "themer"` is set. Not sure why as I know to little of how that's supposed to work.

**Comment by NarutoXY** [comment]
ah yes i acknowledge the fact that most of the stuff is currently undocumented and there's also #27 to work on. Sorry for that.

you can try the below snippet

```lua
use({
	"narutoxy/themer.lua",
	branch = "dev",
	module = "themer",	-- load it as fast as possible
	config = function()
		require("themer").setup({colorscheme = "dark_cpt"})
	end,
})
```

`main` branch has some bugs which are fixed in `dev`, also `dev` is all set for release and no breaking change is coming for end user.

> also add examples for the API of the dev branch.
the `api/colors.lua` allows you to get the colors of a colorscheme
```lua
require("themer.api.colors")("dark_cpt")
```

**Comment by NarutoXY** [comment]
closing after release
